Pipeline:
  name: PP-StructureV3
  device: gpu
  device_id: 0
  batch_size: 1
  lang: ch
  enable_mkldnn: false
  use_fp16: false
  save_markdown: true
  save_json: true
  max_side_len: 4096

SubModules:
  LayoutDetection:
    module_name: layout_detection
    model_name: PP-DocLayout_plus-L
    model_dir: /home/paddleocr/.paddlex/official_models/PP-DocLayout_plus-L_infer
    limit_side_len: 4096
    limit_type: max
  TextDetection:
    module_name: text_detection
    model_name: PP-OCRv5_server_det
    model_dir: /home/paddleocr/.paddlex/official_models/PP-OCRv5_server_det_infer
    limit_side_len: 4096
    limit_type: max
    max_side_limit: 4096
    thresh: 0.3
    box_thresh: 0.6
    unclip_ratio: 1.5
  TextRecognition:
    module_name: text_recognition
    model_name: PP-OCRv5_server_rec
    model_dir: /home/paddleocr/.paddlex/official_models/PP-OCRv5_server_rec_infer
    batch_size: 1
    score_thresh: 0
  TextOrientation:
    module_name: text_orientation
    model_name: PP-LCNet_x1_0_doc_ori
    model_dir: /home/paddleocr/.paddlex/official_models/PP-LCNet_x1_0_doc_ori_infer
  TableDetection:
    module_name: table_detection
    model_name: RT-DETR-L_wired_table_cell_det
    model_dir: /home/paddleocr/.paddlex/official_models/RT-DETR-L_wired_table_cell_det_infer
    limit_side_len: 4096
    limit_type: max
  TableClassification:
    module_name: table_classification
    model_name: PP-LCNet_x1_0_table_cls
    model_dir: /home/paddleocr/.paddlex/official_models/PP-LCNet_x1_0_table_cls_infer

SubPipelines:
  GeneralOCR:
    pipeline_name: OCR
    text_type: general
    use_doc_preprocessor: false
    use_textline_orientation: true
    use_doc_orientation: true
    SubModules:
      LayoutDetection: LayoutDetection
      TextDetection: TextDetection
      TextRecognition: TextRecognition
      TextOrientation: TextOrientation
  TableRecognition:
    pipeline_name: Table
    SubModules:
      LayoutDetection: LayoutDetection
      TextDetection: TextDetection
      TextRecognition: TextRecognition
      TextOrientation: TextOrientation
      TableDetection: TableDetection
      TableClassification: TableClassification

